parameters:
  - name: env
    type: string
  - name: condition
    default: succeeded()
  - name: agentPool
    type: string
  - name: serviceName
    type: string
jobs:
  - deployment: "Deploy_${{ parameters.env }}"
    displayName: "Deploy ${{ parameters.env }}"
    timeoutInMinutes: 300
    environment: aks-cd-${{ parameters.env }}
    pool: ${{ parameters.agentPool }}
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
              path: source
              clean: true
            - checkout: commons
              path: commons
              clean: true
            - task: PowerShell@2
              displayName: "Install Chart"
              inputs:
                targetType: "inline"
                script: |
                  $appVersion = "$(Build.BuildNumber)"
                  helm create ${{ parameters.serviceName }}
                  ls -la ${{ parameters.serviceName }}
                pwsh: true
                workingDirectory: "$(Pipeline.Workspace)/commons/common/aks/helm"
            - task: PowerShell@2
              displayName: "Prepare chart"
              inputs:
                targetType: "inline"
                script: |
                  $appVersion = "$(Build.BuildNumber)"
                  $chartVersion = "$(major).$(minor).$(patch)"
                  Write-Host "App version: $appVersion"
                  Write-Host "Chart version: $chartVersion"
                  Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
                  Install-Module powershell-yaml -Confirm:$false 

                  Write-Host "Prepare Chart.yaml"
                  $yaml = Get-Content -Path Chart.yaml | Out-String
                  $chart = ConvertFrom-Yaml $yaml
                  $chart['name']=  "${{ parameters.serviceName }}"
                  $chart['description']=  "A Helm chart for Kubernetes ${{ parameters.serviceName }}: ${{ parameters.env }}"
                  $chart['version'] = "$chartVersion"
                  $chart['appVersion'] = $appVersion
                  ConvertTo-Yaml $chart | Out-File -Path Chart.yaml
                  Write-Host "==== Prepared Chart ====="
                  Get-Content Chart.yaml

                  #Write-Host " Prepare _helpers.tpl"
                  #$helpers = (Get-Content -Path "templates/_helpers.tpl").Replace('TBD', '${{ parameters.serviceName }}')
                  #$helpers
                  Write-Host "==== Created Chart ====="
                  Get-Content "${{ parameters.serviceName }}/Chart.yaml"
                pwsh: true
                workingDirectory: "$(Pipeline.Workspace)/commons/common/aks/helm"
            - task: AzureCLI@2
              displayName: "Helm upgrade"
              inputs:
                azureSubscription: ${{ variables.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  set -e
                  export HELM_EXPERIMENTAL_OCI=1
                  az aks get-credentials --name $(aksName) --resource-group $(aksResourceGroup) --overwrite-existing
                  kubectl config use-context $(aksName)

                  echo "Prepare working directories"
                  rm -rf $(Pipeline.Workspace)/prep

                  # templates application values tpl through helm
                  echo "Generate values.yaml"
                  cp -r $(Pipeline.Workspace)/commons/aks/helm $(Pipeline.Workspace)/prep
                  ls -la $(Pipeline.Workspace)/prep
                  rm -rf $(Pipeline.Workspace)/prep/templates/*.yaml
                  cp values.${{ parameters.env }}.tpl.yaml $(Pipeline.Workspace)/prep/templates/
                  helm template $(Pipeline.Workspace)/prep -f $(Pipeline.Workspace)/commons/common-values.yaml  --set env=${{ parameters.env }}  > $(Pipeline.Workspace)/helm/values.yaml
                  cat $(Pipeline.Workspace)/helm/values.yaml
                  rm -rf $(Pipeline.Workspace)/prep

                  echo "Helm lint"
                  cd $(Pipeline.Workspace)/helm/
                  ls -la
                  helm lint -f values.yaml -f ../commons/common-values.yaml -n ${{ parameters.env }} --set env=${{ parameters.env }} --set fullnameOverride=$(repoName)
                  helm template . -f values.yaml -f ../commons/common-values.yaml --set env=${{ parameters.env }} --set fullnameOverride=$(repoName) --debug

                  echo "Helm upgrade"
                  helm upgrade -f values.yaml -f ../commons/common-values.yaml -n ${{ parameters.env }} --install --create-namespace --wait $(repoName) --set env=${{ parameters.env }} --set fullnameOverride=$(repoName) .

                  echo "Clean-up"
                  rm -rf $(Pipeline.Workspace)/helm
                addSpnToEnvironment: true
                ${{ if eq(variables.helmRoot, '')}}:
                  workingDirectory: "$(Pipeline.Workspace)/source/helm"
                ${{ if ne(variables.helmRoot, '')}}:
                  workingDirectory: "$(Pipeline.Workspace)/source/${{ variables.helmRoot }}"
              enabled: false
