parameters:
  - name: env
    type: string
  - name: condition
    default: succeeded()
jobs:
  - deployment: "Deploy_${{ parameters.env }}"
    displayName: "Deploy ${{ parameters.env }}"
    timeoutInMinutes: 300
    variables:
      - name: folderName
        value: ${{ variables.projectName }}/
    environment: aks-cd-${{ parameters.env }}
    pool: ${{ variables.agentPool }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
              path: source
              clean: true
            - checkout: commons
              path: commons
              clean: true
            - task: PowerShell@2
              displayName: "Generate common variables"
              inputs:
                targetType: "inline"
                script: |
                  Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
                  Install-Module powershell-yaml -Confirm:$false 
                  $infra_vars = Get-Content common/variables/${{ parameters.env }}.tpl.yaml | ConvertFrom-Yaml 
                  $aks_vars =  Get-Content aks/variables/${{ parameters.env }}.tpl.yaml | ConvertFrom-Yaml

                  # Todos: merger two hashtables with same keys
                  $aks_vars.variables += $infra_vars.variables
                  $values = @{"common"=$aks_vars.variables}

                  ConvertTo-Yaml $values | Out-File -Path ./common-values.yaml
                  Get-Content ./common-values.yaml
                pwsh: true
                workingDirectory: $(Pipeline.Workspace)/commons
            - task: PowerShell@2
              displayName: "Prepare chart"
              inputs:
                targetType: "inline"
                script: |
                  $appVersion = "$(Build.BuildNumber)"
                  Write-Host "Deployment only: ${{ parameters.deploymentOnly }}"
                  if ("${{ parameters.deploymentOnly }}" -eq "True") {
                    $appVersion = "${{ parameters.dockerTagOverride }}"
                  }
                  if (("$appVersion" -eq "") -or ("$appVersion" -eq " ")) {
                    Write-Host "Invalid app version"
                    exit 1
                  }
                  Write-Host "App version: $appVersion"
                  Write-Host "Chart version: $(major).$(minor).$(patch)"
                  Write-Host "Prepare helm templates"
                  if (Test-Path "$(Pipeline.Workspace)/helm") {
                    Remove-Item -Recurse -Force "$(Pipeline.Workspace)/helm"
                  }
                  Copy-Item -Path "$(Pipeline.Workspace)/commons/aks/helm" -Destination "$(Pipeline.Workspace)/helm" -Recurse

                  Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
                  Install-Module powershell-yaml -Confirm:$false 

                  Write-Host "Prepare Chart.yaml"
                  $yaml = Get-Content -Path Chart.yaml | Out-String
                  Write-Host $yaml
                  $chart = ConvertFrom-Yaml $yaml
                  $chart['version'] = "$(major).$(minor).$(patch)"
                  $chart['appVersion'] = $appVersion
                  ConvertTo-Yaml $chart | Out-File -Path $(Pipeline.Workspace)/helm/Chart.yaml

                  Write-Host "Updated Chart.yaml"
                  Get-Content $(Pipeline.Workspace)/helm/Chart.yaml
                pwsh: true
                ${{ if eq(variables.helmRoot, '')}}:
                  workingDirectory: "$(Pipeline.Workspace)/source/helm"
                ${{ if ne(variables.helmRoot, '')}}:
                  workingDirectory: "$(Pipeline.Workspace)/source/${{ variables.helmRoot }}"
            - task: AzureCLI@2
              displayName: "Helm upgrade"
              inputs:
                azureSubscription: ${{ variables.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  set -e
                  export HELM_EXPERIMENTAL_OCI=1
                  az aks get-credentials --name $(aksName) --resource-group $(aksResourceGroup) --overwrite-existing
                  kubectl config use-context $(aksName)

                  echo "Prepare working directories"
                  rm -rf $(Pipeline.Workspace)/prep

                  # templates application values tpl through helm
                  echo "Generate values.yaml"
                  cp -r $(Pipeline.Workspace)/commons/aks/helm $(Pipeline.Workspace)/prep
                  ls -la $(Pipeline.Workspace)/prep
                  rm -rf $(Pipeline.Workspace)/prep/templates/*.yaml
                  cp values.${{ parameters.env }}.tpl.yaml $(Pipeline.Workspace)/prep/templates/
                  helm template $(Pipeline.Workspace)/prep -f $(Pipeline.Workspace)/commons/common-values.yaml  --set env=${{ parameters.env }}  > $(Pipeline.Workspace)/helm/values.yaml
                  cat $(Pipeline.Workspace)/helm/values.yaml
                  rm -rf $(Pipeline.Workspace)/prep

                  echo "Helm lint"
                  cd $(Pipeline.Workspace)/helm/
                  ls -la
                  helm lint -f values.yaml -f ../commons/common-values.yaml -n ${{ parameters.env }} --set env=${{ parameters.env }} --set fullnameOverride=$(repoName)
                  helm template . -f values.yaml -f ../commons/common-values.yaml --set env=${{ parameters.env }} --set fullnameOverride=$(repoName) --debug

                  echo "Helm upgrade"
                  helm upgrade -f values.yaml -f ../commons/common-values.yaml -n ${{ parameters.env }} --install --create-namespace --wait $(repoName) --set env=${{ parameters.env }} --set fullnameOverride=$(repoName) .

                  echo "Clean-up"
                  rm -rf $(Pipeline.Workspace)/helm
                addSpnToEnvironment: true
                ${{ if eq(variables.helmRoot, '')}}:
                  workingDirectory: "$(Pipeline.Workspace)/source/helm"
                ${{ if ne(variables.helmRoot, '')}}:
                  workingDirectory: "$(Pipeline.Workspace)/source/${{ variables.helmRoot }}"
