parameters:
  - name: env
    type: string
    default: dev
  - name: condition
    default: succeeded()
  - name: serviceName
    type: string

stages:
  - stage: "CD_${{ parameters.env }}"
    condition: ${{ parameters.condition }}
    displayName: "Deploy ${{ parameters.env }}"
    jobs:
      - template: job.yaml
        parameters:
          env: ${{ parameters.env }}
          agentPool: $(agentPool)
          serviceName: ${{ parameters.serviceName }}
