{{- if .Values.keyvault }}
{{- range $key, $value := .Values.keyvault.vaults }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ include "immigration.fullname" $ | lower }}-{{ $key | lower }}"
spec:
  provider: azure
  {{- with $value.secretObjects }}
  secretObjects:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.keyvault.userAssignedIdentityID }}
    keyvaultName: {{ $value.name }}
    cloudName: "AzurePublicCloud"
    objects: |
    {{- $value.objects | nindent 6 }}
    tenantId: {{ $.Values.keyvault.tenantId }}
{{- end }}
{{- end }}