parameters:
  - name: acrname
    type: string
  - name: agentPool
    type: string
  - name: repo
    type: string
  - name: dockerBuildContext
    type: string
  - name: dockerfile
    type: string
  - name: condition
    default: succeeded()
  - name: arguments
    type: string

jobs:
  - job: App_Build_Push_ACR
    displayName: "Build & Push ${{ parameters.acrname }}"
    pool: ${{ parameters.agentPool }}
    steps:
      - download: none
      - checkout: self
      - task: Docker@2
        displayName: 'Build and Push to ACR: ${{ parameters.acrname }}'
        inputs:
          containerRegistry: ${{ parameters.acrname }}
          repository: ${{ parameters.repo }}
          Dockerfile: ${{ parameters.dockerfile }}
          buildContext: ${{ parameters.dockerBuildContext }}
          command: 'build'
          arguments: '--build-arg FEED_ACCESSTOKEN=4a66bs3c3nkyxb4salqtuffwxlqhdxsaxrkewmizlu4qsaj2df6a'
          # ${{ if ne(variables.arguments, '')}}:
          #   arguments: ${{ parameters.arguments }}
          tags: '$(Build.BuildNumber)'
        enabled: true
      - task: Docker@2
        displayName: Docker Push
        inputs:
          containerRegistry: ${{ parameters.acrname }}
          repository: ${{ parameters.repo }}
          command: 'push'
          tags: '$(Build.BuildNumber)'
