parameters:
  - name: env
    type: string
  - name: condition
    default: succeeded()

jobs:
  - deployment: "Build_and_Push_${{ parameters.env }}"
    displayName: "Build & Push ${{ parameters.env }}"
    timeoutInMinutes: 300
    variables:
      - name: agentPool
        value: 'Azure Pipelines'
      - name: dockerBuildContext
        value: 'src/backend'
      - name: dockerfile
        value: 'src/backend/ContingentWorkApi/Dockerfile'
    environment: aks-ci-${{ parameters.env }}
    pool: ${{ variables.agentPool }}
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
            - task: Docker@0
              displayName: 'Build an image'
              inputs:
                azureSubscription: 'SPN-WE-COER-C-N002'
                azureContainerRegistry: '{"loginServer":"zwecoercrd001.azurecr.io", "id" : "/subscriptions/b3b5afcf-283b-451d-ada1-0cfaacb75058/resourceGroups/VZI-WE-NP-RG-COER-D002/providers/Microsoft.ContainerRegistry/registries/ZWECOERCRD001"}'
                dockerFile: src/backend/ContingentWorkApi/Dockerfile
                defaultContext: false
                context: src/backend
                imageName: 'vialto/test'
              enabled: false
            - task: Docker@2
              displayName: "Docker Build"
              inputs:
                command: build
                containerRegistry: 'zwecoercrd001'
                repository: 'vialto:test'
                tags: |
                  $(Build.BuildNumber)
                  latest
                buildContext: ${{ variables.dockerBuildContext }}
                Dockerfile: ${{ variables.dockerfile }}
                enabled: false
              - task: Docker@2
                displayName: buildAndPush
                inputs:
                  containerRegistry: ZWECOERCRD001
                  repository: 'vialto:test'
                  Dockerfile: src/backend/ContingentWorkApi/Dockerfile
                  buildContext: src/backend
                  tags: |
                    $(Build.BuildId)
                    latest
                enabled: true