parameters:
  - name: isbuild
    type: string
    default: true
  - name: env
    type: string
  - name: condition
    default: succeeded()

stages:
  - stage: "CI_${{ parameters.env }}"
    condition: ${{ parameters.condition }}
    displayName: "Build and Push Image"
    jobs:
      - template: job.yaml
        parameters:
          env: ${{ parameters.env }}