parameters:
  - name: acrname
    type: string
    default: 'ZWECOERCRD001'
  - name: agentPool
    type: string
    default: 'Azure Pipelines'
  - name: repo
    default: 'vialto/test'
  - name: dockerBuildContext
    default: 'src/backend'
  - name: dockerfile
    default: 'src/backend/ContingentWorkApi/Dockerfile'
  - name: condition
    default: succeeded()

stages:
  - stage: "Build_&_Push"
    condition: ${{ parameters.condition }}
    displayName: "Build and Push Image"
    jobs:
      - template: job-without-env.yaml
        parameters:
          acrname: ${{ parameters.acrname }}
          repo: ${{ parameters.repo }}
          agentPool: ${{ parameters.agentPool }}
          dockerBuildContext: ${{ parameters.dockerBuildContext }}
          dockerfile: ${{ parameters.dockerfile }}
