parameters:
  - name: acrname
    type: string
    default: 'ZWEIMMGCRD001'
  - name: agentPool
    type: string
    default: 'Immigration_Linux_Agent'
  - name: repo
    default: 'vialto/test'
  - name: dockerBuildContext
    default: '$(Build.SourcesDirectory)/Immigration'
  - name: dockerfile
    default: '$(Build.SourcesDirectory)/Immigration/Vialto.Immigration.Web.Api.Employment/Dockerfile'
  - name: condition
    default: succeeded()
  - name: arguments
    default: '--build-arg FEED_ACCESSTOKEN=pbrn4yytgha3bf5pq3s52baikr2ehjzvrocj5e3rzsaguddrcu2q'
stages:
  - stage: "Build__Push"
    condition: ${{ parameters.condition }}
    displayName: "Build and Push Image"
    jobs:
      - template: job-without-env.yaml
        parameters:
          acrname: ${{ parameters.acrname }}
          repo: ${{ parameters.repo }}
          agentPool: ${{ parameters.agentPool }}
          dockerBuildContext: ${{ parameters.dockerBuildContext }}
          dockerfile: ${{ parameters.dockerfile }}
          arguments: ${{ parameters.arguments }}
